""" adding role column in user table

Revision ID: 12d7dfaed7d6
Revises: 46d2508a7cfb
Create Date: 2024-07-02 14:30:09.882588

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '12d7dfaed7d6'
down_revision: Union[str, None] = '46d2508a7cfb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('books', sa.Column('role', sa.String(), nullable=True), schema='sample')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('books', 'role', schema='sample')
    # ### end Alembic commands ###
