""" adding role column in author table

Revision ID: 68618ca6f1d6
Revises: 03d8fd71dc2d
Create Date: 2024-07-02 14:27:36.600204

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '68618ca6f1d6'
down_revision: Union[str, None] = '03d8fd71dc2d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    
    op.add_column('author', sa.Column('role', sa.String(), nullable=True), schema='sample')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('author', 'role', schema='sample')
    
    # ### end Alembic commands ###
