"""create author table

Revision ID: 3d789076df70
Revises: 
Create Date: 2024-06-26 17:57:24.640730

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3d789076df70'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('author',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('user_name', sa.String(), nullable=False),
    sa.Column('password', sa.String(), nullable=False),
    sa.Column('mail', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id',name="PK_author_id"),
    sa.UniqueConstraint('mail'),
    schema='sample'
    )
    op.create_index(op.f('ix_sample_author_user_name'), 'author', ['user_name'], unique=True, schema='sample')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_sample_author_user_name'), table_name='author', schema='sample')
    op.drop_table('author', schema='sample')
    # ### end Alembic commands ###
