"""create publisher table

Revision ID: 6f274cb0db00
Revises: 3d789076df70
Create Date: 2024-06-26 17:58:07.834914

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6f274cb0db00'
down_revision: Union[str, None] = '3d789076df70'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('publisher',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id',name="PK_publisher_id"),
    sa.UniqueConstraint('name'),
    schema='sample'
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('publisher', schema='sample')
    # ### end Alembic commands ###
