"""create user table

Revision ID: b368ce70c671
Revises: 6f274cb0db00
Create Date: 2024-06-26 17:58:31.830146

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b368ce70c671'
down_revision: Union[str, None] = '6f274cb0db00'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('user_name', sa.String(), nullable=False),
    sa.Column('password', sa.String(), nullable=False),
    sa.Column('mail', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id',name="PK_user_id"),
    sa.UniqueConstraint('mail'),
    schema='sample'
    )
    op.create_index(op.f('ix_sample_user_user_name'), 'user', ['user_name'], unique=True, schema='sample')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_sample_user_user_name'), table_name='user', schema='sample')
    op.drop_table('user', schema='sample')
    # ### end Alembic commands ###
